name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request: {}

jobs:
  lint:
    name: ğŸ§ª Test, ğŸ§¹ ESLint, ğŸ‘” Stylelint, ğŸ’… Prettier, and Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ğŸ—„ï¸ Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ğŸ”„ Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ§° Install dependencies
        run: pnpm install

      - name: â¬£ Build project
        run: pnpm build

      - name: ğŸ§ª Run tests
        run: pnpm test

      - name: ğŸ§¹ Lint code
        run: pnpm lint:next

      - name: ğŸ‘” Check styles
        run: pnpm check-styles

      - name: ğŸ’… Check formatting
        run: pnpm check-format

      - name: Ê¦ Check types
        run: pnpm check-types

  # cypress-run:
  #   name: ğŸŒ² Cypress Tests
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - name: â” Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: ğŸ“¦ Install pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: ğŸ—„ï¸ Get pnpm store directory
  #       shell: bash
  #       run: |
  #         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

  #     - name: ğŸ”„ Cache pnpm dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ env.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-

  #     - name: ğŸ§° Install dependencies
  #       run: pnpm install

  #     # - run: mv .env.example .env
  #     - name: ğŸŒ Run Cypress tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         build: pnpm build
  #         start: pnpm start
